package com.devhouse.financial_plan.application.transaction;

import com.devhouse.financial_plan.application.transaction.dto.TransactionResponse;
import com.devhouse.financial_plan.application.transaction.dto.UpdateTransactionRequest;
import com.devhouse.financial_plan.domain.BankAccount;
import com.devhouse.financial_plan.domain.Category;
import com.devhouse.financial_plan.domain.PaymentMethod;
import com.devhouse.financial_plan.domain.SubCategory;
import com.devhouse.financial_plan.domain.Transaction;
import com.devhouse.financial_plan.domain.enums.TransactionType;
import com.devhouse.financial_plan.domain.exception.DomainException;
import com.devhouse.financial_plan.domain.repository.BankAccountRepository;
import com.devhouse.financial_plan.domain.repository.CategoryRepository;
import com.devhouse.financial_plan.domain.repository.PaymentMethodRepository;
import com.devhouse.financial_plan.domain.repository.SubCategoryRepository;
import com.devhouse.financial_plan.domain.repository.TransactionRepository;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Service
public class UpdateTransactionService {

    private final TransactionRepository transactionRepository;
    private final BankAccountRepository bankAccountRepository;
    private final CategoryRepository categoryRepository;
    private final SubCategoryRepository subCategoryRepository;
    private final PaymentMethodRepository paymentMethodRepository;
    private final TransactionBalanceEffectService balanceEffectService;

    public UpdateTransactionService(TransactionRepository transactionRepository, BankAccountRepository bankAccountRepository,
                                     CategoryRepository categoryRepository, SubCategoryRepository subCategoryRepository,
                                     PaymentMethodRepository paymentMethodRepository,
                                     TransactionBalanceEffectService balanceEffectService) {
        this.transactionRepository = transactionRepository;
        this.bankAccountRepository = bankAccountRepository;
        this.categoryRepository = categoryRepository;
        this.subCategoryRepository = subCategoryRepository;
        this.paymentMethodRepository = paymentMethodRepository;
        this.balanceEffectService = balanceEffectService;
    }

    @Transactional
    public TransactionResponse execute(Long id, UpdateTransactionRequest request) {
        Transaction transaction = transactionRepository.findById(id);
        if (transaction.isLinkedToSource()) {
            throw new DomainException("Cannot edit a transaction generated by a bill/invoice payment");
        }
        transaction.setVersion(request.version());
        Transaction old = snapshot(transaction);

        BankAccount bankAccount = resolveBankAccount(request.bankAccountId(), "Bank account not found");
        BankAccount destinationBankAccount = null;
        Category category = null;
        PaymentMethod paymentMethod = null;
        if (TransactionType.TRANSFER.equals(request.type())) {
            destinationBankAccount = resolveBankAccount(request.destinationBankAccountId(), "Destination bank account not found");
        } else {
            category = resolveCategory(request.categoryId());
            paymentMethod = resolvePaymentMethod(request.paymentMethodId());
        }
        SubCategory subCategory = resolveSubCategory(request.subCategoryId());

        balanceEffectService.revert(old);

        transaction.update(request.type(), bankAccount, destinationBankAccount, category, subCategory, paymentMethod,
                request.amount(), request.transactionDate(), request.description());
        transaction.validate();
        balanceEffectService.apply(transaction);

        Transaction updated = transactionRepository.update(transaction);
        return toResponse(updated);
    }

    private Transaction snapshot(Transaction transaction) {
        return new Transaction(transaction.getId(), transaction.getVersion(), transaction.getType(), transaction.getUser(),
                transaction.getBankAccount(), transaction.getDestinationBankAccount(), transaction.getCategory(),
                transaction.getSubCategory(), transaction.getPaymentMethod(), transaction.getAmount(),
                transaction.getTransactionDate(), transaction.getDescription(), transaction.getCreatedDate(),
                transaction.getUpdatedDate(), transaction.getSourceType(), transaction.getSourceId());
    }

    private BankAccount resolveBankAccount(Long bankAccountId, String errorMessage) {
        BankAccount bankAccount = bankAccountId != null ? bankAccountRepository.findById(bankAccountId) : null;
        if (bankAccount == null) {
            throw new DomainException(errorMessage);
        }
        return bankAccount;
    }

    private Category resolveCategory(Long categoryId) {
        Category category = categoryId != null ? categoryRepository.findById(categoryId) : null;
        if (category == null) {
            throw new DomainException("Category not found");
        }
        return category;
    }

    private PaymentMethod resolvePaymentMethod(Long paymentMethodId) {
        PaymentMethod paymentMethod = paymentMethodId != null ? paymentMethodRepository.findById(paymentMethodId) : null;
        if (paymentMethod == null) {
            throw new DomainException("Payment method not found");
        }
        return paymentMethod;
    }

    private SubCategory resolveSubCategory(Long subCategoryId) {
        if (subCategoryId == null) {
            return null;
        }
        SubCategory subCategory = subCategoryRepository.findById(subCategoryId);
        if (subCategory == null) {
            throw new DomainException("Sub category not found");
        }
        return subCategory;
    }

    private TransactionResponse toResponse(Transaction t) {
        return new TransactionResponse(t.getId(), t.getVersion(), t.getType(), t.getUser().getId(), t.getBankAccount().getId(),
                t.getDestinationBankAccount() != null ? t.getDestinationBankAccount().getId() : null,
                t.getCategory() != null ? t.getCategory().getId() : null,
                t.getSubCategory() != null ? t.getSubCategory().getId() : null,
                t.getPaymentMethod() != null ? t.getPaymentMethod().getId() : null, t.getAmount(),
                t.getTransactionDate(), t.getDescription(), t.getCreatedDate());
    }
}
