spring.application.name=financial-plan

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/financial_plan
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update

auth0.domain: financial-plan.us.auth0.com
auth0.audience: https://financial-plan-api

app.frontend-url=${APP_FRONTEND_URL:http://localhost:3000}

spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=${MAILTRAP_USERNAME:}
spring.mail.password=${MAILTRAP_PASSWORD:}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


