import type { ThemeDefinition } from 'vuetify'

export const staticPrimaryColor = '#3E6B4F'
export const staticPrimaryDarkenColor = '#1F3D2F'

export const themes: Record<string, ThemeDefinition> = {
  light: {
    dark: false,
    colors: {
      'primary': staticPrimaryColor,
      'on-primary': '#FFFDF8',
      'primary-darken-1': '#1F3D2F',
      'secondary': '#9FB39A',
      'on-secondary': '#1A1C18',
      'secondary-darken-1': '#8A9E85',
      'success': '#3E6B4F',
      'on-success': '#FFFDF8',
      'success-darken-1': '#1F3D2F',
      'info': '#00BAD1',
      'on-info': '#fff',
      'info-darken-1': '#00A7BC',
      'warning': '#C9A24B',
      'on-warning': '#1A1C18',
      'warning-darken-1': '#A6792F',
      'error': '#B5483A',
      'on-error': '#FFFDF8',
      'error-darken-1': '#9A3B2E',
      'background': '#FFFDF8',
      'on-background': '#1A1C18',
      'surface': '#FBF8F1',
      'on-surface': '#1A1C18',
      'grey-50': '#FAFAF8',
      'grey-100': '#F5F2EA',
      'grey-200': '#EFEADD',
      'grey-300': '#E6DFCF',
      'grey-400': '#DAD1BC',
      'grey-500': '#B8B09E',
      'grey-600': '#8A8279',
      'grey-700': '#5C5F57',
      'grey-800': '#3A3C36',
      'grey-900': '#1A1C18',
      'grey-light': '#FBF8F1',
      'perfect-scrollbar-thumb': '#DAD1BC',
      'skin-bordered-background': '#FBF8F1',
      'skin-bordered-surface': '#FBF8F1',
      'expansion-panel-text-custom-bg': '#F5F2EA',
    },

    variables: {
      'code-color': '#d400ff',
      'overlay-scrim-background': '#1A1C18',
      'tooltip-background': '#1A1C18',
      'overlay-scrim-opacity': 0.5,
      'hover-opacity': 0.06,
      'focus-opacity': 0.1,
      'selected-opacity': 0.08,
      'activated-opacity': 0.16,
      'pressed-opacity': 0.14,
      'dragged-opacity': 0.1,
      'disabled-opacity': 0.4,
      'border-color': '#1A1C18',
      'border-opacity': 0.12,
      'table-header-color': '#EFEADD',
      'high-emphasis-opacity': 0.9,
      'medium-emphasis-opacity': 0.7,
      'switch-opacity': 0.2,
      'switch-disabled-track-opacity': 0.3,
      'switch-disabled-thumb-opacity': 0.4,
      'switch-checked-disabled-opacity': 0.3,
      'track-bg': '#EFEADD',

      // Shadows
      'shadow-key-umbra-color': '#1A1C18',
      'shadow-xs-opacity': 0.10,
      'shadow-sm-opacity': 0.12,
      'shadow-md-opacity': 0.14,
      'shadow-lg-opacity': 0.16,
      'shadow-xl-opacity': 0.18,
    },
  },
  dark: {
    dark: true,
    colors: {
      'primary': staticPrimaryColor,
      'on-primary': '#FFFDF8',
      'primary-darken-1': '#1F3D2F',
      'secondary': '#9FB39A',
      'on-secondary': '#1A1C18',
      'secondary-darken-1': '#8A9E85',
      'success': '#3E6B4F',
      'on-success': '#FFFDF8',
      'success-darken-1': '#1F3D2F',
      'info': '#00BAD1',
      'on-info': '#fff',
      'info-darken-1': '#00A7BC',
      'warning': '#C9A24B',
      'on-warning': '#1A1C18',
      'warning-darken-1': '#A6792F',
      'error': '#B5483A',
      'on-error': '#FFFDF8',
      'error-darken-1': '#9A3B2E',
      'background': '#1A1C18',
      'on-background': '#FFFDF8',
      'surface': '#2A2C26',
      'on-surface': '#FFFDF8',
      'grey-50': '#2A2C26',
      'grey-100': '#2A2C26',
      'grey-200': '#1A1C18',
      'grey-300': '#3A3C36',
      'grey-400': '#5C5F57',
      'grey-500': '#8A8279',
      'grey-600': '#B8B09E',
      'grey-700': '#DAD1BC',
      'grey-800': '#EFEADD',
      'grey-900': '#FBF8F1',
      'grey-light': '#2A2C26',
      'perfect-scrollbar-thumb': '#3A3C36',
      'skin-bordered-background': '#2A2C26',
      'skin-bordered-surface': '#2A2C26',
    },
    variables: {
      'code-color': '#d400ff',
      'overlay-scrim-background': '#0A0C08',
      'tooltip-background': '#FBF8F1',
      'overlay-scrim-opacity': 0.6,
      'hover-opacity': 0.06,
      'focus-opacity': 0.1,
      'selected-opacity': 0.08,
      'activated-opacity': 0.16,
      'pressed-opacity': 0.14,
      'dragged-opacity': 0.1,
      'disabled-opacity': 0.4,
      'border-color': '#FFFDF8',
      'border-opacity': 0.12,
      'table-header-color': '#3A3C36',
      'high-emphasis-opacity': 0.9,
      'medium-emphasis-opacity': 0.7,
      'switch-opacity': 0.4,
      'switch-disabled-track-opacity': 0.4,
      'switch-disabled-thumb-opacity': 0.8,
      'switch-checked-disabled-opacity': 0.3,
      'track-bg': '#2A2C26',

      // Shadows
      'shadow-key-umbra-color': '#0A0C08',
      'shadow-xs-opacity': 0.16,
      'shadow-sm-opacity': 0.18,
      'shadow-md-opacity': 0.2,
      'shadow-lg-opacity': 0.22,
      'shadow-xl-opacity': 0.24,
    },
  },
}

export default themes
